name: build check

on:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "22"
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.json"

      - name: install
        run: pnpm install

      - name: build
        run: pnpm run build
