name: build check

on:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with: 
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: install
        run: npm ci

      - name: build
        run: npm run build
      
      - name: export
        run: npm run export
