name: SFTP Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with: 
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: install
        run: npm ci

      - name: build
        run: npm run build
      
      - name: export
        run: npm run export

      - name: Upload to server
        uses: wangyucode/sftp-upload-action@v2.0.3
        with:
          host: 'wycode.cn'
          username: ${{ secrets.SERVER_USERNAME }}
          privateKey: ${{ secrets.SERVER_KEY }}
          localDir: 'out'
          dryRun: false
          compress: true
          remoteDir: '/root/data/www/wycode/'
          removeExtraFilesOnServer: true

      - name: Deploy to Github pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          repo: wangyucode/wangyucode.github.io
          target_branch: master
          build_dir: out
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_PUSH_TOKEN }}

      - name: Send posts to algolia
        run: npm run algolia ${{ secrets.ALGOLIA_KEY }}

      - name: Send Email
        run: |
          curl -m 10 -i -X POST \
            -H "Content-Type:application/json" \
            -d \
            '{"key": "${{ secrets.MAIL_TOKEN }}","subject":"Frontend Build","content":"frontend deployed","to": "wangyu@wycode.cn"}' \
            'https://wycode.cn/api/v1/email'
