name: SFTP Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: build
        run: pnpm run build

      - name: export
        run: pnpm run export

      - name: Upload to server
        uses: wangyucode/sftp-upload-action@v2.0.3
        with:
          host: "wycode.cn"
          username: ${{ secrets.SERVER_USERNAME }}
          privateKey: ${{ secrets.SERVER_KEY }}
          localDir: "out"
          dryRun: false
          compress: true
          remoteDir: "/home/ubuntu/docker/www/wycode/"
          removeExtraFilesOnServer: true

      - name: Deploy to Github pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          repo: wangyucode/wangyucode.github.io
          target_branch: master
          build_dir: out
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_PUSH_TOKEN }}

      - name: Send Email
        run: |
          curl -m 10 -i -X POST \
            -H "Content-Type:application/json" \
            -d \
            '{"key": "${{ secrets.MAIL_TOKEN }}","subject":"Frontend Build","content":"frontend deployed","to": "wangyu@wycode.cn"}' \
            'https://wycode.cn/api/v1/email'
